#!/usr/bin/env bash
# debugging nginx port 80
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# a Bash script that configures a server to the above requirements

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
